-- MySQL Script generated by MySQL Workbench
-- Fri Mar 25 02:11:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SegundoExamen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SegundoExamen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SegundoExamen` DEFAULT CHARACTER SET utf8 ;
USE `SegundoExamen` ;

-- -----------------------------------------------------
-- Table `SegundoExamen`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SegundoExamen`.`usuarios` (
  `Codigo` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SegundoExamen`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SegundoExamen`.`producto` (
  `Id` INT NOT NULL,
  `Codigo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Precio` DECIMAL(15,2) NOT NULL,
  `Inventario` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
